---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2
  log_level: info

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu-14.04.chef_client_12_7_2
suites:
  - name: default
    run_list:
      - recipe[chef-wrapper-consul::default]
    driver:
      vm_hostname: default.local
    attributes:
      consul:
        config:
          server: true
        master:
          instances:
            - "default.local"
